# Generated by Django 2.2.2 on 2019-06-27 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=datetime.datetime(2019, 6, 27, 8, 1, 25, 216079, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
